igl | vulkan | tests | Use /bigobj on Win/MSVC to compile VulkanHelpersTests due to large object file
Summary:
I'm getting `fatal error C1128` when compiling `VulkanHelpersTest.cpp`:

  fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj

So I'm adding `/bigobj` when compiling IGLTests on Win/MSVC

Reviewed By: corporateshark

Differential Revision: D61678041

fbshipit-source-id: b00289345532537f208d9e7128c06b6e23647e65