igl | shell | XrApp : fix Xr constructor errors
Summary:
switch to brace initialization to fix this error

```
/home/runner/work/igl/igl/shell/openxr/mobile/XrApp.cpp:1071:14: error: no matching constructor for initialization of 'XrExtent2Df'
        size = XrExtent2Df(glmSize.x, glmSize.y);
```

Reviewed By: tgoulart, KyleFung, corporateshark

Differential Revision: D56040028

fbshipit-source-id: 9215d2bf393d4fb5e437c06483537e362789cd8e